### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocBaseUtils#1]
@LiNk-NY @mtmorgan Can we discuss the name of the package here and reach consensus _before_ renaming the repo?

Initial **BiocUtils** was not bad. I only suggested that we add a middle word that tries to give a sense of the kind of utilities that are in the package, that is, nothing that the end-user will ever see or use directly, but low-level things that are used internally by other packages.

I suggested "Internal" for the middle word. Things like "Base" or "Core" are reasonable alternatives if you are worried that "Internal" could imply that the package is intended for the Bioc-core. Personally I think that only a few Bioc-core members might actually be biased into this, not the community in general, so to me this not an issue. I'm against using "Devel" as middle word as this suggests that the package (**BiocDevelUtils**) is some kind of Bioconductor version of **devtools**, or, more generally speaking, is some package used actively during the development of a package to automate some tasks, like packages **roxygen2** or **codetoolsBioC**.

I don't like naming a package according to its target audience (**BiocDeveloper**). As a developer myself I'd rather see a name that gives me an idea of what the package contains. But that name doesn't tell me anything, except that the package might contain stuff that might be of interest to me as a developer. The name of CRAN package **assert** tells me what the package is about so is a good name. Thankfully they didn't decide to name it **developer**!

So my proposals are, in order of preference: (1) **BiocInternalUtils**, (2) **BiocBaseUtils**, (3) **BiocCoreUtils**. Any of those 3 would satisfy me.

Also open to other suggestions.

Thanks,
H.

**Comment by mtmorgan** [comment]
I'm listed as 'ctb' but I haven't actively contributed (I guess I'm a ctb because some of my original code is being used). I haven't developed an opinion on package name and wasn't involved in package renaming discussions. I did state a preference when talking with Marcel for `isScalarCharacter()` etc (because R has a character type but not a string type) but said at the time that it wasn't my decision to make...

**Comment by LiNk-NY** [comment]
Hi Hervé, @hpages 

Thanks for opening up this issue. My point about the "internal" comment is that it feels too exclusive to the rest community. The `BiocDeveloper` name is an attempt to have a package that is open to contributions.

It does not mean that packages such as `BiocInternalUtils`, `BiocBaseUtils`, `BiocCoreUtils`, etc. cannot be direct dependencies. Given the split feedback between the usage of "internals" and "utilities", I thought it would be better to have a general package name geared towards the intended audience. 

FWIW, we didn't raise these questions when we decided to use `BiocManager` as a name. One could argue that the name is also not specific enough and make a case for `BiocPackageInstaller`. 

As with any package, advertising gives users a general idea of what a package is about. 

I don't mind renaming the package as long as we all agree. Think `BiocBaseUtils` sounds too close to `Biobase` and the other options sound inclusive to only Bioc-core developers. I can additionally suggest `BiocUtilities`. 

Best regards,
Marcel

**Comment by hpages** [comment]
> FWIW, we didn't raise these questions when we decided to use BiocManager as a name.

Again, for **BiocInternalUtils** the length of the name is not an issue because no end user will ever have to type it. This is a big difference with **BiocManager** that is very much an end user package, so it's important to keep its name relatively short, easy to remember, and easy to type. I personally type its name every day to run `BiocManager::install()` at the beginning of my first R session of the day. Naming the package **BiocPackageInstaller** would have made this a PITA without adding much value. BTW the package provides additional facilities that are not strictly about installing packages.

Also, if IIRC, in the end the name of the **BiocManager** package was publicly discussed and voted.

> Think BiocBaseUtils sounds too close to Biobase.

Well, the "Utils" suffix has a powerful disambiguation effect if you ask me. And we're used to have many "base" packages already e.g. **base**, **GSEABase**, **GGBase**, **a4Base**, **basecallQC**, **BaseSpaceR**, **biovizBase**, **Pbase**, and many more... Never been a problem. Note that **biovizBase** is in a situation similar to **BiocBaseUtils** i.e. not meant to be used directly by the user but provides a set of utilities meant to be used by high-level packages for biological data visualization.

H.

**Comment by LiNk-NY** [comment]
I cast my vote for `BiocBaseUtilities`. 
Any thoughts / preferences Martin? @mtmorgan

**Comment by mtmorgan** [comment]
No preference!

**Comment by hpages** [comment]
Anything wrong with having "utils" in a package name?
```
> bioc_pkgs <- rownames(available.packages(contrib.url("https://bioconductor.org/packages/3.15/bioc")))

> grep("utils", bioc_pkgs, ignore.case=TRUE, value=TRUE)
 [1] "basilisk.utils"  "clstutils"       "DropletUtils"    "flowUtils"      
 [5] "MetaboCoreUtils" "MsCoreUtils"     "QSutils"         "TCGAutils"      
 [9] "TFutils"         "TrajectoryUtils"

> grep("utilities", bioc_pkgs, ignore.case=TRUE, value=TRUE)
character(0)
```
Also:
```
hpages@spectre:~$ apt-cache search --names-only utils | wc -l
778

hpages@spectre:~$ apt-cache search --names-only utilities | wc -l
16
```

**Comment by LiNk-NY** [comment]
I think it's better to avoid abbreviations but `Bioc` is also an abbreviation. We can go with `BiocBaseUtils`. 
Thanks!

**Comment by hpages** [comment]
Sounds good. Glad we made it. Thanks!
